export const GROUPS_LOADING = "GROUPS_LOADING";
export const GROUPS_SET_DATA = "GROUPS_SET_DATA";
export const GROUPS_REMOVE_DATA = "GROUPS_REMOVE_DATA";
export const GROUPS_ADD_DATA = "GROUPS_ADD_DATA";
export const GROUPS_RESET="GROUPS_RESET";